### PR TITLE
Adding a email field to student registration

### PR DESCRIPTION
**Pull request by YarinBou**
Small PR just for adding some field that wasn't saved.

### CODE REVIEW

**Review by benmenachem — APPROVED** [review]

**Review by guyy13 — APPROVED** [review]
lgtm

**Review by yaelerdr — APPROVED** [review]

**Review by yaelerdr — APPROVED** [review]
👌👌

**Review by eldaraharonson — APPROVED** [review]

**Comment by ifireball** [comment]
Seems like there was a bug... why did the tests not catch it? I would expect to see an expansion to the tests that would catch it from now on.

**Comment by YarinBou** [comment]
I will add an expansion to the tests that will check this field.

**Review by ifireball — APPROVED** [review]

**Pull request merged**
