### PR TITLE
Added design to the recruiter & student registration form

### PR DESCRIPTION
**Pull request by benmenachem**
Created design for the Recruiter&Student registration form. Needs to be merged after PR #82 
Has the exact same design as in PR's #82 #84 #85 .

Screen Shot 2021-12-29 at 9 19 34 AM

Screen Shot 2021-12-29 at 9 20 21 AM

when you press the button it changes to be this way: 

Screen Shot 2021-12-27 at 10 30 43 PM

### CODE REVIEW

**Review by guyy13 — COMMENTED** [review]
For some reason, the button is white and not green as defined in the CSS file.
Besides that lgtm.

**Review by YarinBou — APPROVED** [review]

**Comment by guy9050** [comment]
Usually WIP is in the beggining. i.e WIP: Added design to the recruiter & student registration form

**Comment by benmenachem** [comment]
> Usually WIP is in the beggining. i.e WIP: Added design to the recruiter & student registration form

@guy9050 fixed it. it will be ready for review after PR #84 will be merged

**Review by guyy13 — APPROVED** [review]

**Review by eldaraharonson — APPROVED** [review]

**Review by yaelerdr — APPROVED** [review]

**Comment by benmenachem** [comment]
> For some reason, the button is white and not green as defined in the CSS file.
> Besides that lgtm.

@guyy13 fixed.

**Review by guy9050 — APPROVED** [review]
lgtm

**Pull request merged**
