### PR TITLE
Created the basic job_application model.  And separating it from the jobboard app

### LINKED ISSUE #41: Create job_application models

### PR DESCRIPTION
**Pull request by YarinBou**
closes #41

### CODE REVIEW

**Comment by guy9050** [comment]
pytest check fail

**Comment by YarinBou** [comment]
yeah, I'm checking why is that. because I didn't change the recruiter and student files at all.

**Comment by YarinBou** [comment]
> pytest check fail

done.

**Comment by guyy13** [comment]
Squash the commits

**Review by guyy13 — APPROVED** [review]

**Review by eldaraharonson — APPROVED** [review]

**Review by benmenachem — APPROVED** [review]

**Comment by ifireball** [comment]
Sine I see changes in the jobboard model and migrations files that are not explained in the pr description, I cannot safely merge this. Furthermore, I don't expect to see migration files being changed once they were merged.

**Comment by YarinBou** [comment]
I did not quite understand you.
Do you want me to add in the PR description exactly what I deleted in these files? General description of
deleting application from jobboarb is not enough?  Or is the problem that it appears in the commit and not in the main description?

**Comment by ifireball** [comment]
For now the biggest issue seems to be that similar changes were done in another PR and you have a conflict

**Comment by YarinBou** [comment]
> For now the biggest issue seems to be that similar changes were done in another PR and you have a conflict

yeah, I'm on it.

**Review by ifireball — APPROVED** [review]
I don't see the value of this for the demo given there is no business logic or tests, but merging anyway.

**Pull request merged**
