### PR TITLE
Re-created the Django project and configured a home page

### PR DESCRIPTION
**Pull request by guyy13**
Re-created the Django project in order to rename it to 'SJMaster'.
Also created a jobboard app and changed the homepage of the project.

### CODE REVIEW

**Review by benmenachem — APPROVED** [review]

**Review by yaelerdr — APPROVED** [review]

**Comment by ifireball** [comment]
I've ni idea why you guys are approving this PR! I'm still seeing files named "beyond-tutorial" in this PR. You are not writing a tutorial! You are writing a real project! Please give things proper names!

**Comment by ifireball** [comment]
I now see you already have "beyond-tutorial" files merged in your repo. Not sure who merged that but it shouldn't have passed review. Please mere a new PR to delete all those files and then create your Django project properly from scratch!

**Comment by guyy13** [comment]
> I now see you already have "beyond-tutorial" files merged in your repo. Not sure who merged that but it shouldn't have passed review. Please mere a new PR to delete all those files and then create your Django project properly from scratch!

A new PR was created to change the Django project name: #17 
Will update this PR accordingly after #17 is merged.

**Comment by ifireball** [comment]
I still see attempts to rename the old file - pelase don't try that - it can cause issues in the long run - please delete the old project files, commit that and then create a new project form scratch

**Comment by guyy13** [comment]
> I still see attempts to rename the old file - pelase don't try that - it can cause issues in the long run - please delete the old project files, commit that and then create a new project form scratch

I deleted all of the old project files and created a new project from scratch, not sure why it shows up like I renamed the files.
Should I try to commit the deletion of the project separately? (For a total of 3 commits).

**Comment by ifireball** [comment]
> > I still see attempts to rename the old file - pelase don't try that - it can cause issues in the long run - please delete the old project files, commit that and then create a new project form scratch
> 
> I deleted all of the old project files and created a new project from scratch, not sure why it shows up like I renamed the files. Should I try to commit the deletion of the project separately? (For a total of 3 commits).

yes please. that way I can know this is really what is going on

**Comment by guyy13** [comment]
> > > I still see attempts to rename the old file - pelase don't try that - it can cause issues in the long run - please delete the old project files, commit that and then create a new project form scratch
> > 
> > 
> > I deleted all of the old project files and created a new project from scratch, not sure why it shows up like I renamed the files. Should I try to commit the deletion of the project separately? (For a total of 3 commits).
> 
> yes please. that way I can know this is really what is going on

Ok, done.

**Review by ifireball — APPROVED** [review]
Now LGTM

**Comment by guy9050** [comment]
it still looks as if it was renamed. maybe better to split into two PR's? @ifireball

**Comment by ifireball** [comment]
It just looks that way if you ask to view the cumulative differences from all commits (That is what the "files changed" tab shows you). If you look at the commits individually you can see the full process..

**Review by eldaraharonson — APPROVED** [review]

**Review by dmaizel — APPROVED** [review]

**Review by guy9050 — APPROVED** [review]

**Review by YarinBou — APPROVED** [review]

**Pull request merged**
