### PR TITLE
Design for 'recruiter/myjobs' page

### PR DESCRIPTION
**Pull request by guyy13**
Added a design for the 'myjobs' page.
The job name is in green, below you can see the applicants for each job.

myjobsfixed

### CODE REVIEW

**Review by YarinBou — APPROVED** [review]

**Review by eldaraharonson — COMMENTED** [review]
I feel like the green font on the purple background doesn't really match (on the job name), maybe keep it white but just change the font style?
Other than that looks great!

**Comment by guyy13** [comment]
> I feel like the green font on the purple background doesn't really match (on the job name), maybe keep it white but just change the font style? Other than that looks great!

Yea I feel you, I think I'll change it to white

**Review by benmenachem — APPROVED** [review]
looks good

**Review by eldaraharonson — APPROVED** [review]
Nice!

**Review by yaelerdr — APPROVED** [review]

**Review by ifireball — APPROVED** [review]

**Pull request merged**
