### PR TITLE
Edited login page

### PR DESCRIPTION
**Pull request by benmenachem**
Edited the design of the login page 
Most of it is based on the existing css 

Screen Shot 2021-12-28 at 8 09 29 PM

### CODE REVIEW

**Review by guyy13 — APPROVED** [review]
lgtm

**Review by yaelerdr — APPROVED** [review]

**Review by YarinBou — APPROVED** [review]

**Review by eldaraharonson — APPROVED** [review]

**Review by guy9050 — APPROVED** [review]
pls change the commit message to something more understandable than "edited login page"

**Comment by guy9050** [comment]
pls change the commit message to something more understandable than "edited login page"

**Comment by benmenachem** [comment]
> pls change the commit message to something more understandable than "edited login page"

@guy9050 changed the commit to mention that the PR takes care of the CSS of the page

**Review by ifireball — APPROVED** [review]

**Pull request merged**
