### PR TITLE
Create new job page design

### PR DESCRIPTION
**Pull request by guyy13**
Changed the design of the 'Create new job' page.

Screenshot:
Create_new_job

### CODE REVIEW

**Review by YarinBou — APPROVED** [review]

**Review by eldaraharonson — APPROVED** [review]

**Review by benmenachem — APPROVED** [review]

**Review by yaelerdr — APPROVED** [review]

**Comment by guy9050** [comment]
Still WIP?

**Comment by guyy13** [comment]
> Still WIP?

Yes because it depends on the changes on #84

**Comment by guy9050** [comment]
> > Still WIP?
> 
> Yes because it depends on the changes on #84

then it's not WIP but Blocked.

And it's important because people will not review WIP PR's but blocked means that it's ready for review

**Comment by guyy13** [comment]
> > > Still WIP?
> > 
> > 
> > Yes because it depends on the changes on #84
> 
> then it's not WIP but Blocked.
> 
> And it's important because people will not review WIP PR's but blocked means that it's ready for review

It's not ready to review though, I will have to change all the code in this PR once #84 is merged since currently, I am not sure how to implement the design in the template. After we conclude how to do that on #84 then I'll be able to write the code for this PR properly.

**Comment by guyy13** [comment]
The first commit is from #84, once it's merged this PR can be merged.

**Review by benmenachem — APPROVED** [review]

**Review by YarinBou — APPROVED** [review]

**Review by yaelerdr — APPROVED** [review]

**Comment by guyy13** [comment]
Rebased

**Review by eldaraharonson — APPROVED** [review]

**Review by benmenachem — APPROVED** [review]

**Review by eldaraharonson — APPROVED** [review]

**Review by YarinBou — APPROVED** [review]

**Review by yaelerdr — APPROVED** [review]

**Review by ifireball — APPROVED** [review]

**Pull request merged**
