### PR TITLE
Fixed project's name created by django

### PR DESCRIPTION
**Pull request by yaelerdr**
Fixed the django project file's name from "beyond_tutorial" to "SJMaster"
Also, fixed "beyond_tutorial" to "SJMaster" inside - settings.py, asgi.py, urls.py and wsgi.py

### CODE REVIEW

**Comment by guyy13** [comment]
Please also change the following line in the "manage.py" file from
`os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'beyond_tutorial.settings')`
to:
`os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'SJMaster.settings')`
Then it should work.

**Review by guyy13 — APPROVED** [review]

**Comment by ifireball** [comment]
@yaelerdr did you delete the old files like I asked and start from scratch of are you trying to somehow fix the existing files?

Please do as I've asked, trying to change the files once they were created will jut cause issues down the line. I expect to see 2 commits in the name change PR - one that deletes the old files and antoehr that creates the project from scratch.

If we had time I would have asked for this to be done in separate PRs.

**Review by ifireball — CHANGES_REQUESTED** [review]
Please fix this PR ASAP. You will not be allowed to include unmerged code in the demo!

**Comment by yaelerdr** [comment]
> Please also change the following line in the "manage.py" file from `os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'beyond_tutorial.settings')` to: `os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'SJMaster.settings')` Then it should work.

**Comment by yaelerdr** [comment]
@guyy13 created new PR with those 2 commits were requested

**Pull request closed without merging**
