### PR TITLE
Created Login app

### PR DESCRIPTION
**Pull request by yaelerdr**
Created Login app from vagrant.
Commented unused imports for flake8 not to complaint.
Added Login app on settings.py

### CODE REVIEW

**Review by eldaraharonson — APPROVED** [review]

**Review by ifireball — APPROVED** [review]

**Review by benmenachem — APPROVED** [review]

**Review by dmaizel — APPROVED** [review]

**Review by guyy13 — APPROVED** [review]

**Review by YarinBou — APPROVED** [review]

**Review by guy9050 — APPROVED** [review]

**Comment by guy9050** [comment]
Please fix the conflicts

**Comment by yaelerdr** [comment]
> Please fix the conflicts
done

**Comment by yaelerdr** [comment]
> Please fix the conflicts

done

**Comment by ifireball** [comment]
I just noticed the name of the APP here is `Login` with capital `L`. Since Django apps are also Python modules, its better the have the name be all lowercase to match the usual Python naming conventions.

**Comment by yaelerdr** [comment]
@ifireball  Ok. I'm closing this PR and will create a new one

**Pull request closed without merging**
