### PR TITLE
Jobboard functions and tests

### PR DESCRIPTION
**Pull request by eldaraharonson**
1. Removed Application model since we were instructed to put it in a
    seperate app.
2. Added functions to the Job model that fetch jobs based on certain
    criteria regarding the jobs' attributes.
3. Added tests for those functions.

### CODE REVIEW

**Review by benmenachem — APPROVED** [review]

**Review by YarinBou — APPROVED** [review]

**Comment by guyy13** [comment]
Could you try to minimize the use of fixtures and use the example data that's already in the DB instead?

**Review by guyy13 — APPROVED** [review]

**Comment by ifireball** [comment]
I'm seeing merged migration files being changed, I cannot safely merge this

**Review by ifireball — CHANGES_REQUESTED** [review]
Do not change merged migration files, create new ones.

**Comment by guyy13** [comment]
> Do not change merged migration files, create new ones.

@ifireball 
I fixed it.
The only migrations file that is modified is the one with the example data. We needed more data for the tests, made sense to add the new data to the already existing file.

**Review by ifireball — APPROVED** [review]
While changing test data migrations is also something you shouldn't do, because it can break staging systems if you have any, since you don't have one for now, I'm letting it pass

**Pull request merged**
