### PR TITLE
login and registration basic working functionality

### PR DESCRIPTION
**Pull request by YarinBou**
should be merged after guy PR #57 to the navigation page.

### CODE REVIEW

**Comment by guyy13** [comment]
Look awesome!
But I think we should use Django Forms instead of creating the form manually with HTML, it will make our life much easier.

**Comment by YarinBou** [comment]
will be fixed, just after I will learn how to use it this weekend. believe the next version will be upload on  ~ Sunday.

**Comment by eldaraharonson** [comment]
I know that Yael created a login app in the project as well. Shouldn't the sign up and login forms be there instead of the jobboard app? If not then we should delete the login app since it is empty anyway.

**Review by benmenachem — APPROVED** [review]

**Review by guyy13 — CHANGES_REQUESTED** [review]
I think we need to use the built in django login and register pages. (I just learnt they exist).

**Comment by YarinBou** [comment]
Hey, I update the login and registration pages to use Django. I have a few problems there. 
I worked according to this tutorial - https://ordinarycoders.com/blog/article/django-user-register-login-logout
maybe one of you will show me my mistake? something with the login and the logout doesn't work right.  
will be happy to talk with someone (tomorrow maybe) about this. anyway, good night and take a look, please. :)

**Comment by YarinBou** [comment]
still having some troubles with my login function.

**Comment by guy9050** [comment]
since this is not ready, please add "WIP:" in the headline or make it draft, so people won't review this

**Review by guyy13 — APPROVED** [review]
LGTM!

**Comment by guy9050** [comment]
Did you manage to resolve the issues you had?

**Comment by YarinBou** [comment]
Yes

**Comment by YarinBou** [comment]
I finished today the login, logout and registration functionality, and pages. working great. 
this is the first stage for the MVP, they will be improved.

**Comment by YarinBou** [comment]
just squash all my Commits.

**Comment by guy9050** [comment]
nice work!

**Comment by YarinBou** [comment]
Thanks guy

**Pull request merged**
